export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_CURRENCIES = 'SET_CURRENCIES';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_BALANCES = 'SET_BALANCES';
export const SET_INVESTMENT_FUNDS = 'SET_INVESTMENT_FUNDS';
export const SET_INVESTMENT_FUND_SHARES = 'SET_INVESTMENT_FUND_SHARES';
export const SET_INVESTMENT_FUND_BALANCE_UPDATES = 'SET_INVESTMENT_FUND_BALANCE_UPDATES';
